version: 0.0
os: linux

files:

  - source: /
    destination: /usr/local/tomcat8/webapps/webapp/target
  - source: /webapp/src/main/webapp/index.jsp
    destination: /usr/local/tomcat8/webapps/webapp/target
 
file_exists_behavior: OVERWRITE    
          
hooks:
  ApplicationStop:
    - location: scripts/server_stop.sh
      timeout: 180
      runas: root
  BeforeInstall:
    - location: scripts/server_uninstall.sh
      timeout: 180
      runas: root 
  AfterInstall:
    - location: scripts/server_start.sh
      timeout: 180
      runas: root
