version: 0.0
os: linux

files:
  - source: /webapp/src/main/webapp/WEB-INF/
    destination: /usr/local/tomcat8/webapps/

file_exists_behavior: OVERWRITE    
          
hooks:
  ApplicationStop:
    - location: scripts/server_stop.sh
      timeout: 60
      runas: root
  BeforeInstall:
    - location: scripts/server_uninstall.sh
      timeout: 60
      runas: root 
  AfterInstall:
    - location: scripts/server_start.sh
      timeout: 60
      runas: root
