version: 0.0
os: linux

files:
  - source: /var/lib/jenkins/.m2/repository/com/example/maven-project/webapp/1.0-SNAPSHOT/webapp-1.0-SNAPSHOT.war
    destination: /usr/local/tomcat8/webapps/
  - source: /webapp/src/main/webapp/index.jsp
    destination: /usr/local/tomcat8/webapps/

file_exists_behavior: OVERWRITE    
          
hooks:
  ApplicationStop:
    - location: scripts/server_stop.sh
      timeout: 60
      runas: root
  BeforeInstall:
    - location: scripts/server_uninstall.sh
      timeout: 60
      runas: root 
  AfterInstall:
    - location: scripts/server_start.sh
      timeout: 60
      runas: root
